version: "3.8"

services:
  ci_mongo:
    image: mongo:6.0
    container_name: ci_mongo
    volumes:
      - ci_mongo_data:/data/db
    networks:
      - ci-network
    restart: unless-stopped

  ci_backend:
    image: node:18-bullseye
    container_name: ci_backend
    working_dir: /app
    volumes:
      - backend_code:/app
      - /app/node_modules
    ports:
      - "7000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URL=mongodb://ci_mongo:27017/ci_db
    command: sh -c "npm install --silent && npm start"
    depends_on:
      - ci_mongo
    networks:
      - ci-network
    restart: unless-stopped

  ci_frontend:
    image: node:18-bullseye
    container_name: ci_frontend
    working_dir: /app
    volumes:
      - frontend_code:/app
      - /app/node_modules
    ports:
      - "8081:80"
    environment:
      - REACT_APP_BASE_URL=http://16.171.155.132:7000/api
    command: sh -c "npm install --silent && npm run build && npx serve -s build -l 80"
    depends_on:
      - ci_backend
    networks:
      - ci-network
    restart: unless-stopped

volumes:
  ci_mongo_data:
    driver: local
  backend_code:
    driver: local
  frontend_code:
    driver: local

networks:
  ci-network:
    driver: bridge
