version: "3.8"

services:
  ci_mongo:
    image: mongo:6.0
    container_name: ci_mongo
    restart: always
    volumes:
      - ci_mongo_data:/data/db
    networks:
      - ci-network

  ci_backend:
    image: node:18-bullseye
    container_name: ci_backend
    working_dir: /app
    volumes:
      - ./backend:/app:cached
    ports:
      - "5000:5000"       # Host 5000 -> Container 5000 (same as Part 1)
    environment:
      - NODE_ENV=production
    command: sh -c "npm install --silent && npm start"
    depends_on:
      - ci_mongo
    networks:
      - ci-network

  ci_frontend:
    image: node:18-bullseye
    container_name: ci_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app:cached
    ports:
      - "8081:80"         # Host 8081 -> Container 80
    environment:
      - REACT_APP_BASE_URL=http://16.171.155.132:5000/api   # Calls backend on 5000
    command: sh -c "npm install --silent && npm run build && npm install -g serve && serve -s build -l 80"
    depends_on:
      - ci_backend
    restart: always
    networks:
      - ci-network

volumes:
  ci_mongo_data:

networks:
  ci-network:
    driver: bridge
