version: "3.8"

services:
  ci_mongo:
    image: mongo:6.0
    container_name: ci_mongo
    restart: "no"
    volumes:
      - ci_mongo_data:/data/db
    networks:
      - ci-network

  ci_backend:
    image: node:18-alpine
    container_name: ci_backend
    working_dir: /app
    volumes:
      - ./backend:/app:cached
    ports:
      - "6000:5000"    # host:container -> backend will be reachable on host port 6000
    command: sh -c "npm install --silent && npm run start"
    depends_on:
      - ci_mongo
    networks:
      - ci-network

  ci_frontend:
    image: node:18-alpine
    container_name: ci_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app:cached
    ports:
      - "8081:80"      # host:container -> frontend will be reachable on host port 8081
    command: sh -c "npm install --silent && npm run build && npx serve -s build -l 80"
    depends_on:
      - ci_backend
    networks:
      - ci-network

volumes:
  ci_mongo_data:

networks:
  ci-network:
    driver: bridge
